version: "3.8"

networks:
  local_net:
    name: local_net
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    ports:
      - 5433:5432
    expose:
      - 5432
    
    environment:
      - POSTGRES_DB=reddit
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD=*Admin.369*
      - POSTGRES_HOST=localhost
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      local_net:
        aliases:
          - postgres_host

  python:
    container_name: python
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=reddit
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD=*Admin.369*
    volumes:
      - ./apiReddit:/code
    depends_on:
      - postgres
    networks:
      local_net:
        aliases:
          - python_host